server:
  port: 9000

spring:
  main:
    web-application-type: none
  application:
    name: university-tg-speech-bot
  jpa:
    database: postgresql
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

speech-synthesizer-bot:
  telegram-api:
    bot-token:
    bot-username: "speech synthesizer"
  yandex-api:
    token:
    folder-id:
  yandex-iam-api:
    url: https://iam.api.cloud.yandex.net/iam
    path: /v1/tokens
  yandex-speech-api:
    url: https://tts.api.cloud.yandex.net/speech
    path: /v1/tts:synthesize


